fix: missing import in ContainerSecurity class
Creating an instance of `ContainerSecurity` without passin in credentials raises an exception:
```
Traceback (most recent call last):
  File "/Users/tim.birkett/Projects/docker-tenable-cleanup/tenable_cleanup.py", line 39, in <module>
    cs = ContainerSecurity(access_key=TENABLE_ACCESS_KEY, secret_key=TENABLE_SECRET_KEY)
  File "/Users/tim.birkett/Projects/docker-tenable-cleanup/venv/lib/python3.9/site-packages/tenable/cs/__init__.py", line 99, in __init__
    self._access_key = os.getenv('TIO_ACCESS_KEY')
NameError: name 'os' is not defined
```

This fixes that issue.